### ISSUE TITLE
Mount encrypted external disk.

### ISSUE THREAD

**Issue by hobbldygoop** [libyal/libfvde#1]
I'm trying to mount some encrypted external drives, all created under 10.9 with either DiskUtility or Finder(rightlick encrypt). Based on what I've read on the wiki that should be mountable like this:

```
$> sudo fvdemount -p "mypass" /dev/sdb2 /mnt/fvde/
fvdemount 20140907

Unable to unlock keys.
```

I always get this error, I'm certain that the password is correct.
Is this not supported or am I missing something?

**Comment by orzechow** [comment]
I have the same issue. Multiple partitions on a GUID partitioned external disk. One of those is the encrypted Apple_CoreStorage.

**Comment by joachimmetz** [comment]
Made some changes to improve format support: https://github.com/libyal/libfvde/commit/811bd2685ba232543c771a69418ff9203aab1a09

**Comment by orzechow** [comment]
Nice! Now `fvdemount` is working, but I'm still failing to mount it, because `mount` doesn't recognize the file system...
What I'm doing is: 

    sudo fvdemount -X allow_root -p "mypass" /dev/sdb2 /media/TimeMachine
    sudo mount -o loop,ro /media/TimeMachine/fvde1 /media/TimeMachineMount/

The error is: 

    mount: you must specify the filesystem type

As you say in your [presentation](http://www.cl.cam.ac.uk/~osc22/docs/slides_fv2_ifip_2013.pdf) the underlying file system should be HFS+
So I tried to add the file system option `-t hfsplus`, but it says

    mount: wrong fs type, bad option, bad superblock on /dev/loop0,
       missing codepage or helper program, or other error
       In some cases useful info is found in syslog - try
       dmesg | tail  or so

and `dmesg | tail` prints a.o.:

    hfsplus: unable to find HFS+ superblock

`sudo fsck.hfsplus -q /media/TimeMachine/fvde1` prints:

    ** /media/carolo11/TimeMachine/fvde1 (NO WRITE)
    QUICKCHECK ONLY; NO HFS SIGNATURE FOUND

I might run into an Ubuntu problem here (see [bug 279110] (https://bugs.launchpad.net/ubuntu/+bug/279110) and [bug 1386493] (https://bugs.launchpad.net/ubuntu/+source/hfsplus/+bug/1386493) ), but I didn't find enough proof for that and don't have another Linux OS to check that...
So maybe you have any idea what's going on?

Btw. that's my disks formatting (I'm trying to access the "Time Machine Backup"):

    Model: Generic External (scsi)
    Disk /dev/sdb: 500GB
    Sector size (logical/physical): 512B/512B
    Partition Table: gpt
    
    Number  Start   End    Size    File system  Name                  Flags
     1      20,5kB  210MB  210MB   fat32        EFI System Partition  boot
     2      210MB   286GB  285GB                Time Machine Backup
     3      286GB   286GB  134MB   hfs+         Booter
     4      286GB   425GB  139GB   hfs+         Untitled
     5      425GB   500GB  74,9GB  fat32        Untitled              msftdata

**Comment by joachimmetz** [comment]
It is more likely that libfvde does not parse the metadata correctly. Verbose and debug output should tell you if the unencrypted volume header is found correctly.

**Comment by salumaee** [comment]
I have similiar problem with encrypted system disk.
I want access to "Untitled" partition:
```
# mmls /dev/sda
GUID Partition Table (EFI)
Offset Sector: 0
Units are in 512-byte sectors

     Slot    Start        End          Length       Description
00:  Meta    0000000000   0000000000   0000000001   Safety Table
01:  -----   0000000000   0000000039   0000000040   Unallocated
02:  Meta    0000000001   0000000001   0000000001   GPT Header
03:  Meta    0000000002   0000000033   0000000032   Partition Table
04:  00      0000000040   0000409639   0000409600   EFI System Partition
05:  01      0000409640   1952255367   1951845728   Untitled
06:  02      1952255368   1953525127   0001269760   Recovery HD
07:  -----   1953525128   1953525167   0000000040   Unallocated

# fls -r -o 1952255368 /dev/sda | grep -i EncryptedRoot
+++++ r/r 1726:	EncryptedRoot.plist.wipekey

# icat -o 1952255368 /dev/sda 1726 > EncryptedRoot.plist.wipekey

# fvdemount -e EncryptedRoot.plist.wipekey -r * /dev/sda2 /mnt/fvdevolume

# mount -o loop,ro -t hfsplus /mnt/fvdevolume/fvde1 /mnt/mac
mount: wrong fs type, bad option, bad superblock on /dev/loop0,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

# dmesg | tail
[ 1960.047589] hfsplus: unable to find HFS+ superblock
```

Verbose and debug output [here](https://www.dropbox.com/s/uak91hmmukvlid5/fvde.log?dl=0)
Do you have any idea what can be wrong?

**Comment by patte** [comment]
I'm running in exactly the same situation as @salumaee :(
```
sudo mount -o loop,ro -t hfsplus  /mnt/fvdevolume/fvde1 /mnt/mac/
mount: wrong fs type, bad option, bad superblock on /dev/loop0,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

dmesg
hfsplus: unable to find HFS+ superblock
```

when running it without -t hfsplus
```
same error
dmesg
[ 1099.486480] blk_update_request: I/O error, dev loop0, sector 1951805568
[ 1099.486596] blk_update_request: I/O error, dev loop0, sector 1951805568
[ 1099.486602] Buffer I/O error on dev loop0, logical block 243975696, async page read
[ 1107.471683] blk_update_request: I/O error, dev loop0, sector 1951805568
[ 1107.471810] blk_update_request: I/O error, dev loop0, sector 1951805568
[ 1107.471817] Buffer I/O error on dev loop0, logical block 243975696, async page read
[ 1107.473699] blk_update_request: I/O error, dev loop0, sector 1951805568
[ 1107.473871] blk_update_request: I/O error, dev loop0, sector 1951805568
[ 1107.473877] Buffer I/O error on dev loop0, logical block 1951805568, async page read
[ 1107.474008] blk_update_request: I/O error, dev loop0, sector 1951805569
[ 1107.474016] Buffer I/O error on dev loop0, logical block 1951805569, async page read
[ 1107.474067] blk_update_request: I/O error, dev loop0, sector 1951805570
[ 1107.474073] Buffer I/O error on dev loop0, logical block 1951805570, async page read
[ 1107.474113] blk_update_request: I/O error, dev loop0, sector 1951805571
[ 1107.474117] Buffer I/O error on dev loop0, logical block 1951805571, async page read
[ 1107.474175] blk_update_request: I/O error, dev loop0, sector 1951805572
[ 1107.474183] Buffer I/O error on dev loop0, logical block 1951805572, async page read
[ 1107.474219] blk_update_request: I/O error, dev loop0, sector 1951805573
[ 1107.474223] Buffer I/O error on dev loop0, logical block 1951805573, async page read
[ 1107.474265] blk_update_request: I/O error, dev loop0, sector 1951805574
[ 1107.474267] Buffer I/O error on dev loop0, logical block 1951805574, async page read
[ 1107.474320] Buffer I/O error on dev loop0, logical block 1951805575, async page read
```

what could I try?

**Comment by willd** [comment]
I ended up dd'ing the fvde1 partition file to a new device, running fsck on that device. I could then mount it properly! (I also fucked up a hfsplus shrink from OSX, which made the installation unusable)

**Comment by echoz** [comment]
Seeing the same as @patte. fsck.hfsplus -f also says the following but doesn't actually repair the volume:

`root@pico:/media# fsck.hfsplus -f fvde/fvde1 
** fvde/fvde1 (NO WRITE)
** Checking HFS Plus volume.
** Checking Extents Overflow file.
** Checking Catalog file.
** Checking Catalog hierarchy.
** Checking Extended Attributes file.
** Checking volume bitmap.
** Checking volume information.
   Volume Header needs minor repair
** The volume Untitled needs to be repaired.`

FV2 external disk was created using disk utility > erase for journaled, encrypted volume on 10.12.3

**Comment by nihilus** [comment]
Had this issue as well and using --force and this FUSE driver https://github.com/0x09/hfsfuse mounted the filesystem.

**Comment by simoneeferreira** [comment]
@nihilus your comment saved me a lifetime of pain and suffering. You, sir, deserves a cup/pint/goblet of whatever beverage you might desire.

Env: Ubuntu 20.04

For anyone with this kind of problem in the future, these were the steps taken that worked for me:

1. Downloaded installed and built fvde (using the .dev section on the wiki).
2. Found the `EncryptedRoot.plist.wipekey` file from recovery
3. `$ sudo fvdemount -v -p <password> -e EncryptedRoot.plist.wipekey /dev/<fvde_drive> /mnt/fuse`
4. Downloaded, compiled and installed hfsfuse (https://github.com/0x09/hfsfuse)
5. `$ hfsfuse -o ro --force /dev/<fvde_device> /mnt/file_system`
6. ???
7. Profit!

Again! thanks @joachimmetz for this lib and @nihilus for the hfsfuse tip.

**Comment by joachimmetz** [comment]
Closing this issue in favor of https://github.com/libyal/libfvde/issues/2
