### ISSUE TITLE
Error - Unable to retrieve element: 1303816 value

### ISSUE THREAD

**Issue by xtaylord** [libyal/libfvde#14]
I've successfully mounted an encrypted volume using the following command:
fvdemount -e EncryptedRoot.plist.wipekey -V -o 209735680 -p 'PASSWORD' imagefile.dd /mnt/tmp/

However, when I try and copy or 'dd' /mnt/tmp/fvde1 I start getting repeated Input/output errors from the imaging tool after reading about 600mb. 

In verbose mode, fvdemount gives the following repeated errors when this point is met:

mount_handle_read_buffer: unable to read buffer from input volume
fvdemount_fuse_read: unable to read from mount handle.
libfvde_sector_data_read: unable to read sector data
libfvde_io_handle_read_sector: unable to read sector data.
libfdata_vector_get_element_value_by_index: unable to read element data at offset: 01c338b2000.
libfdata_vector_get_element_value_at_offset: unable to retrieve element: 1303816 value
libfvde_internal_volume_read_buffer_from_file_io_handle: unable to retrieve sector data at offset: 667553792
libfvde_volume_read_buffer: unable to read buffer.

./fvdeinfo -o 209735680 imagefile.dd
fvdeinfo 20160609
Physical volume:
Size: 120473067520 bytes
Encryption method: AES XTS
Logical volume:
Size: 120108089344 bytes

Any ideas why this is failing?
Thanks

**Comment by joachimmetz** [comment]
> Any ideas why this is failing?

Is you image truncated by any chance?

**Comment by xtaylord** [comment]
I believe it's a complete disk image. I generated an md5 hash when I acquired the image, so I'll verify the hashes tomorrow.

**Comment by xtaylord** [comment]
I've just checked and the hash matches the original disk, confirming that it is a complete image.

**Comment by joachimmetz** [comment]
Thanks, I suspect it might be something with handling the metadata then, that the offset falls outside the image. If you can provide me with a debug log (see: https://github.com/libyal/libfvde/wiki/Troubleshooting#format-or-behavioral-errors) I can try to determine what this issue is.

**Comment by joachimmetz** [comment]
Please also make sure you're using the latest libfvde.

**Comment by joachimmetz** [comment]
Cannot fix without debug.log closing issue, reopen if additional information comes available.
