### ISSUE TITLE
Password Displayed in Process List (security concern)

### ISSUE THREAD

**Issue by dan-saba** [libyal/libfvde#16]
I noticed that fvdemount will display the partition's password in the process list (which can be seen by any user), as it is taken as a parameter when mounting. Can this security issue be corrected in a future release?

**Comment by joachimmetz** [comment]
At the moment this project is **experimental** and the tools are meant for usage in isolated lab environments. I can look into adding an option that allow you to pass credential via a password prompt. Note that this is not one of my highest priorities.

**Comment by dan-saba** [comment]
Thanks for the quick response. May I suggest [this](http://stackoverflow.com/questions/3830823/hiding-secret-from-command-line-parameter-on-unix) as a workaround for those who share this concern?

**Comment by ephemient** [comment]
This is not a proper long-term solution, but I made [libcmdsdaskpass.so](https://gist.github.com/ephemient/daafa8b001a46004f649) to get around this for the time being (on Linux).

    LD_PRELOAD=libcmdsdaskpass.so fvdemount -p '$(systemd-ask-password --id=fvdemount --keyname=cryptsetup --accept-cached)' ...

The password doesn't show up in `/proc/.../cmdline` but the program is executed as if it were there. You can probably modify it to suit your needs.

**Comment by joachimmetz** [comment]
Password related changes integrated in 86e0c5b, closing issue
