### ISSUE TITLE
winapi autodetect logic seems to have an issue

### ISSUE THREAD

**Issue by gregfreemyer** [libyal/libfvde#18]
I'm trying to build libfvde inside the openSUSE build system.  I suspect it is attempting to do a WIndows cross compile.

https://build.opensuse.org/package/show/home:gregfreemyer:Tools-for-forensic-boot-cd/libfvde

If you look at the build log you see the ./confgure process ends with:

[   68s] checking for stdarg.h... (cached) yes
[   68s] checking for varargs.h... (cached) no
[   68s] checking that generated files are newer than configure... done
[   68s] configure: error: conditional "HAVE_WINCRYPT" was never defined.
[   68s] Usually this means the macro was only invoked conditionally.
[   68s] error: Bad exit status from /var/tmp/rpm-tmp.4S1VF9 (%build)

I'm attempting the very basic ./configure statement "./configure " and "./configure--disable-winapi"

Let me know if there is something I'm doing wrong.

Thanks

**Comment by joachimmetz** [comment]
I'll have a look when time permits.

**Comment by joachimmetz** [comment]
This is likely fixed by https://github.com/libyal/libfvde/commit/04e8b4c5e24af4468e0180cdf8d561aa3ed2d0f8

**Comment by gregfreemyer** [comment]
Indeed it is fixed.

Thanks
