### ISSUE TITLE
Can't run (cross-)compiled binary on Windows

### ISSUE THREAD

**Issue by Rob--W** [libyal/libfvde#31]
I cross-compiled for Windows on Linux based on the instructions at https://github.com/libyal/libfvde/wiki/Building.
Instead of MinGW32 I used MinGW-W64, with the following command:

```sh
./configure --host=i686-w64-mingw32 --enable-winapi=yes
```

The above produces a binary (e.g. `fvdeinfo.exe`), but when I run it on Windows 7, I get the following error:

> The program can't start because libgcc_s_sjlj-1.dll is missing from your computer.  Try reinstalling the program to fix this problem.

It seems that `libvfde-1.dll` is dynamically linked against `libgcc_s_sjlj-1.dll`, which is not present on Windows 7 by default. I tried `--enable-static-executables=yes` [as suggested by the wiki](https://github.com/libyal/libfvde/wiki/Building#static-executables), but that didn't compile at all.
I also tried overriding `CFLAGS` and `LDFLAGS`, but that had no effect.

Ultimately I got a working binary with:

```sh
CC=/usr/bin/i686-w64-mingw32-gcc\ -static-libgcc ./configure --host=i686-w64-mingw32 --enable-winapi=yes
```

**Comment by joachimmetz** [comment]
Unclear if this is an issue or an FYI. Documentation mentions that cygwin builds are dependent on other DLLs. Documentation cannot account for every edge case possible, closing issue.
