### ISSUE TITLE
any pre-compiled package for Windows ?

### ISSUE THREAD

**Issue by Lennyroquai** [libyal/libfvde#45]
Dear all,

A thousand sorry... but even by following and trying multiples times : i wasn't able to compile the tool. (Visual studio 2010, mingw, etc...) 
Is there any precompiled packages available somewhere ?

Thank you

**Comment by joachimmetz** [comment]
This project does not provide prebuild binaries. What issue are you running into trying to compile the source yourself?

**Comment by Lennyroquai** [comment]
Dear Joachim,

Sorry for the late answer.
I was finally able to build the package, thanks to the different answers from other people. And the source of the issue was : gigantic lack of knowledge from me :)

I had several issues : 
- Lack of knowledge on Mingw32 and the librairies needed
- Issue compiling in 64 bits (but answered by someone in the issues list)
- Missing the libgcc_s_dw2-1.dll

**Comment by joachimmetz** [comment]
Good to hear you were able to resolve your issues..
