### ISSUE TITLE
cp mounted volume is slow

### ISSUE THREAD

**Issue by christw92** [libyal/libfvde#46]
I decrypted an fvde partition and then mounted this partition (to the external USB 3.0 hdd where the raw file is located too).

Then I tried to copy with cp to another folder on the same external hdd (to store data decrypted).

I'm trying to copy about 90GB of files and inspecting the current progress it would take about 3-4 days to copy this.

Any hints on why this is taking so long? Or is it "normal" when using this tool?

**Comment by joachimmetz** [comment]
this is an experimental project.

Here are tips to troubleshoot https://github.com/libyal/libfvde/wiki/Troubleshooting

> Any hints on why this is taking so long? Or is it "normal" when using this tool?

I've not seen such behavior before with this tool. I opt you take the time to properly troubleshoot you put blame somewhere.

**Comment by christw92** [comment]
Seems like the external hdd I used was corrupted. I used another one (freshly formatted with same file system type) and it copies very fast now :)
