### ISSUE TITLE
Unable to mount fvde1 partition

### ISSUE THREAD

**Issue by TiagonewDEV** [libyal/libfvde#51]
When i try to mount the fvde1 partition i get this error "wrong fs type, bad option, bad superblock on /dev/loop11, missing codepage or helper program, or other error." please help i have a homeworkon this HD

**Comment by joachimmetz** [comment]
@TiagonewDEV are you sure your HD contains CoreStorage with FileVault "Disk" Encryption. This is an older format that is nolonger actively used.

**Comment by TiagonewDEV** [comment]
Yes I'm sure ... It's a mavericks partition soooo

**Comment by joachimmetz** [comment]
@TiagonewDEV then provide some more relevant details. I'm not able to help you if you don't clearly describe what steps you are taking and what issues you're are running into. Also provide the relevant debug output, also see https://github.com/libyal/libfvde/wiki/Troubleshooting#format-or-behavioral-errors

**Comment by TiagonewDEV** [comment]
Don't worry I'm gonna ask someone a Mac
