### ISSUE TITLE
Retrieve hash from wipekey only

### ISSUE THREAD

**Issue by EightLegs** [libyal/libfvde#52]
Good day. 

Is it available to retrieve FileVault hash for hashcat only with .wipekey file?  I have this file but don't have any access to the encrypted volume.

**Comment by joachimmetz** [comment]
@EightLegs what do you mean with "FileVault hash" ?

**Comment by EightLegs** [comment]
> @EightLegs what do you mean with "FileVault hash" ?
I mean a hash string like this example below
$fvde$1$16$3fc886d887bef6f52b6d3f275c290e23$135098$5f852cd981bdad55bd8e60de04ab28742961b3c55e28a0f5

Is it available to retrive a hash like this with only EncryptedRoot.plist.wipekey file? Do i misunderstand anything?

**Comment by joachimmetz** [comment]
> I mean a hash string like this example below

and what does this represent?
