### ISSUE TITLE
libfvde_metadata_block_read_data: unsupported block size: 7312611905704139

### ISSUE THREAD

**Issue by arcticforensics** [libyal/libfvde#53]
[debug.txt](https://github.com/libyal/libfvde/files/7813221/debug.txt)

Same problem as issue #40???

Unable to open source volume
libfvde_metadata_block_read_data: unsupported block size: 7312611905704139.

libfvde_encrypted_metadata_read: unable to read metadata block.

libfvde_volume_open_read: unable to read primary encrypted metadata.

libfvde_volume_open_file_io_handle: unable to read from file IO handle.

mount_handle_open: unable to open volume.

fvdemount version 20210907

**Comment by arcticforensics** [comment]
Same problem as issue #42???

Unable to open source volume
libfvde_metadata_block_read_data: unsupported block size: 7312611905704139.

libfvde_encrypted_metadata_read: unable to read metadata block.

libfvde_volume_open_read: unable to read primary encrypted metadata.

libfvde_volume_open_file_io_handle: unable to read from file IO handle.

mount_handle_open: unable to open volume.

fvdemount version 20210907

**Comment by arcticforensics** [comment]
This may be an issue with earlier versions of Mac OS X.  The error above occurred when attempting to read a thumb drive formatted as a single CoreStorage device (diskutil corestorage create ....) created using Mac OS Yosemite (10.10).  However, formatting an identical thumb drive using the same command with Mac OS Catalina (10.15), fvdemount works!

**Comment by joachimmetz** [comment]
Yes this issue is similar to https://github.com/libyal/libfvde/issues/40, though that it happens after an encrypted metadata block 0x0011 instead of 0x0013.

**Comment by joachimmetz** [comment]
Closing this in favor of https://github.com/libyal/libfvde/issues/40, @arcticforensics if the image can be shared or the test case can be added to https://github.com/dfirlabs/core-storage-specimens that could be useful in determining if this is an unsupported format feature or something else.
