### ISSUE TITLE
Add quickstart guide for new users

### ISSUE THREAD

**Issue by miguelmorin** [libyal/libfvde#58]
I discovered this package on [StackExchange](https://apple.stackexchange.com/questions/371502/which-encrypted-items-show-a-hint/371511?noredirect=1#comment642893_371511) and felt very excited by the possibility of retrieving encrypted data. A [StackExchange user](https://apple.stackexchange.com/questions/444615/find-and-decode-bytes-containing-passphrase-hint-cryptousers-structure-in-file) mentioned: 

> I would just start with the tools supplied. I.e. try running fvdeinfo and fvdemount on it with a lot of verbosity

I installed the package with Python:

```
python setup.py build
sudo python setup.py install
```

But I cannot find the `fvdeinfo` and `fvdemount`:

```
$ which fvdemount
$ which fvdeinfo
$ sudo fvdeinfo
Password:
sudo: fvdeinfo: command not found
```

and the research paper referenced in the `README` does not seem to contain it either.

Could you add in the documentation a quick guide for getting started with `libfvde`?

**Comment by joachimmetz** [comment]
You only built the Python bindings, not the tools. As I said before follow the build instructions https://github.com/libyal/libfvde/wiki there is no mention/recommendation to use setup.py.

**Comment by miguelmorin** [comment]
Indeed, the instructions to [build from source](https://github.com/libyal/libfvde/wiki/Building) contain all the elements for a successful build, and now I see:

```
$ ls  /usr/local/bin/ | grep fvde
fvdeinfo
fvdemount
fvdewipekey
```
