### ISSUE TITLE
Add support for un-encrypted Fusion volumes

### ISSUE THREAD

**Issue by yurikoles** [libyal/libfvde#6]
Or please explain how to mount such volume. Obviuosly, I don't have EncryptedRoot.plist.wipekey on my Recovery HD.
https://gist.github.com/yurikoles/bbce281789e182af873d

**Comment by joachimmetz** [comment]
If you can provide me with debug output or a test image I can have a look.
Also see: https://github.com/libyal/libfvde/wiki/Troubleshooting#verbose-and-debug-output

**Comment by yurikoles** [comment]
I just created fusion drive with disckutil cs commands.

**Comment by joachimmetz** [comment]
I would need to know exactly how you create the cs volume, otherwise I'm unable to reproduce the issue.

**Comment by yurikoles** [comment]
```
diskutil cs create /dev/disk0s4 /dev/disk1s4
diskutil cs createVolume <UUID> jhfs+ Fusion 100%
```

**Comment by joachimmetz** [comment]
Thx I'll have a look as soon as time permits.

**Comment by yurikoles** [comment]
up?

**Comment by joachimmetz** [comment]
None yet.

**Comment by ClintfromCanada** [comment]
Hello.  I would also love to know how I can mount an unencrypted Fusion volume in Linux.  Seems it would be best to just ignore the -e option and have try to mount without a key.  What do I know though...

**Comment by joachimmetz** [comment]
at the moment this is not support, hence this feature request

**Comment by TheAlienDrew** [comment]
Any status on the implementation of this?

**Comment by joachimmetz** [comment]
Looks like the original request is to have support for multiple physical volumes. Closing this issue in favor of https://github.com/libyal/libfvde/issues/54 (also to disambiguate with Fusion Drives).
