### ISSUE TITLE
Question about lib

### ISSUE THREAD

**Issue by xxxmonsterxxx** [libyal/libfvde#65]
As i undestand it could to help me read encrypted via FileVault data? I have too many misstakes and lost login to macos password also recovery vilefault key was lost. I have access to apple id but mac wonnt to use it for recovery. And i know that my recovery key now stored in macos cmd bash history. But i cannot mount volume for read it. 
 
I hope u will answer me.

**Comment by joachimmetz** [comment]
This project and issue tracker is about the FVDE format specifically, which is not the same as FileVault, but was used by FileVault at some point, but no longer. This project is not Apple support or a data recovery service. I'll respond you your email separately.
