### ISSUE TITLE
Is MacOS BigSur supported?

### ISSUE THREAD

**Issue by akasaka99** [libyal/libfvde#66]
Hi, I just came across your project which is great.
I see the tool is valid up to MacOS Catalina  and I wonder whether there are plans to go up to MacOS BigSur and/or Monterey?
Many thamks

**Comment by joachimmetz** [comment]
> I see the tool is valid up to MacOS Catalina and I wonder whether there are plans to go up to MacOS BigSur and/or Monterey?

Where do you base this on?

**Comment by akasaka99** [comment]
On the front page https://github.com/libyal/libfvde  it says:
```
Supported Core Storage / FileVault2 implementations:
* Mac OS X Lion (10.7)
* Mac OS X Mountain Lion (10.8)
* Mac OS X Mavericks (10.9)
* Mac OS X Yosemite (10.10)
* Mac OS X El Capitan (10.11)
* macOS Sierra (10.12)
* macOS High Sierra (10.13)
* macOS Mojave (10.14)
* macOS Catalina (10.15)
```
There's no mention of Big Sur, Monterey and Sonoma.

**Comment by joachimmetz** [comment]
That refer to the CoreStorage format versions, not the source. CoreStorage+FileVault was superseded by APFS on MacOS

**Comment by akasaka99** [comment]
Thank you for clarfication.  
And I see there are two versions for download: 11 Nov 23 and 13 Jan 24 which are for testing.
There's no stable version in between?

**Comment by joachimmetz** [comment]
> There's no stable version in between?

Depends on what you consider as "stable" but per same README the status of this project is experimental. See: https://github.com/libyal/libyal/wiki what is meant by this.

Closing issue given the original question has been answered.

**Comment by akasaka99** [comment]
Ah ok it's a hobby project on sundays
Enjoy
